spring.application.name: api-gateway
server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
jwt.secretKey: yourjwtsecretkey

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: http://posts-service
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connections-service
          uri: http://connections-service
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


