spring.application.name=uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka
cloudinary.cloud-name=dbinubejr
cloudinary.api-key=566281562545682
cloudinary.api-secret=QcXCw98h6h55NZoYoBvUxm4sEfs